### ISSUE TITLE
File is missing (from .ts_augmentations import apply_transformation) 

### ISSUE THREAD

**Issue by mudassar266** [emadeldeen24/ECGTransForm#1]
Hi, 
I hope you are doing well, I am implementing this project. while implementing the code by running the file dataloader.py there is a line (from .ts_augmentations import apply_transformation) in it. This line of code needs to find a directory. But there is no directory with this name. So, its humble request to you to clear this issue. Thank you very much

**Comment by emadeldeen24** [comment]
Thanks a lot for reporting. I cleared that line, as it was not necessary here.
