### ISSUE TITLE
torch.tensor error

### ISSUE THREAD

**Issue by scotwilli** [emadeldeen24/ECGTransForm#2]
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

line no 91:
self.cross_entropy = torch.nn.CrossEntropyLoss(weight=torch.tensor(np.array(self.cw_dict.values())).float().to(self.device))

**Comment by emadeldeen24** [comment]
You can try this fix:
```
weights = [float(value) for value in self.cw_dict.values()]
# Now convert the list of floats to a numpy array, then to a PyTorch tensor
weights_array = np.array(weights).astype(np.float32)  # Ensuring the correct dtype
weights_tensor = torch.tensor(weights_array).to(self.device)
self.cross_entropy = torch.nn.CrossEntropyLoss(weight=weights_tensor)
```

**Comment by emadeldeen24** [comment]
I updated the trainer.py accordingly.
