### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AllGGI** [emadeldeen24/ECGTransForm#3]

**Comment by emadeldeen24** [comment]
It should be like [batch_size, #channels, seq_len]

**Comment by ktovo** [comment]
Can you tell me the requirements for this code？

**Comment by ktovo** [comment]
Why can't I get such a good F1-score based on the source code and processed dataset you gave?

**Comment by ktovo** [comment]
> _No description provided.未提供说明。 _

Did you run out of the F1-score on his paper based on this source code?I really want to know.

**Comment by emadeldeen24** [comment]
@ktovo what performance do you get? Can you share your logs?

**Comment by ktovo** [comment]
[classification_report_best.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965198/classification_report_best.xlsx)
[classification_report_last.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965199/classification_report_last.xlsx)
[classification_report_test.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965200/classification_report_test.xlsx)

**Comment by ktovo** [comment]
> @ktovo what performance do you get? Can you share your logs?
[classification_report_best.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965198/classification_report_best.xlsx)
[classification_report_last.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965199/classification_report_last.xlsx)
[classification_report_test.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965200/classification_report_test.xlsx)

**Comment by ktovo** [comment]
[classification_report_best.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965198/classification_report_best.xlsx)
[classification_report_last.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965199/classification_report_last.xlsx)
[classification_report_test.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/14965200/classification_report_test.xlsx)
@emadeldeen24
