### ISSUE TITLE
f1 score

### ISSUE THREAD

**Issue by ktovo** [emadeldeen24/ECGTransForm#4]
[classification_report_best.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/15006511/classification_report_best.xlsx)
[classification_report_last.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/15006512/classification_report_last.xlsx)
[classification_report_test.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/15006513/classification_report_test.xlsx)
This is my F1 score, why is it so low? @ @emadeldeen24

**Comment by emadeldeen24** [comment]
Hi, 
it looks like I missed something while cleaning the code. I have updated the `dataloader.py`. Please check.

Thanks for reporting.

**Comment by ktovo** [comment]
> Hi, it looks like I missed something while cleaning the code. I have updated the `dataloader.py`. Please check.
> 
> Thanks for reporting.

Thank you very much, I will download it and try it later.
