### ISSUE TITLE
Can't get F1 score in paper based on processed dataset and source code

### ISSUE THREAD

**Issue by splendor1811** [emadeldeen24/ECGTransForm#5]
When I re-implement your code without changing anything, the accuracy on the MIT-BIH set is only 97% and the F1 on test set is only 71%
[classification_report_best (3).xlsx](https://github.com/emadeldeen24/ECGTransForm/files/15144944/classification_report_best.3.xlsx)

**Comment by emadeldeen24** [comment]
I can get different results with the same code
[classification_report_test.xlsx](https://github.com/emadeldeen24/ECGTransForm/files/15171904/classification_report_test.xlsx)

**Comment by splendor1811** [comment]
oh I realized you updated the code so I'll run the code again. Thanks for your respond
